### ISSUE TITLE
Keyboard shrinks the web view on Samsung S4 and S5 (v2.8.1)

### ISSUE THREAD

**Issue by marwonline** [trigger-corp/forge#28] opened 2019-10-15 07:28 UTC
**Device information 1:**
 - Hardware: Samsung S5 (SM-G900F)
 - Operating System and Version: 6.0.1
 - Forge Platform version: v2.8.1

**Device information 2:**
 - Hardware: Samsung S4 (GT-I9505)
 - Operating System and Version: 5.0.1
 - Forge Platform version: v2.8.1

**App information:**

trigger config: 

<details>

```
{
  "config_version": "4",
  "name": "TestApp",
  "author": "marwonline",
  "version": "1.0.0",
  "platform_version": "v2.8.1",
  "core": {
    "general": {
      "logging": {
        "level": "INFO"
      },
      "reload": true,
      "trusted_urls": ["https://localhost/*"],
      "httpd": {
        "port": 9360,
        "url": "https://localhost:9360/src/index.html",
        "certificate_path": "localhost.p12",
        "certificate_password": ""
      }
    },
    "android": {
      "minimum_version": "19",
      "disable_ics_acceleration": true,
      "package_name": "%android_package_name%",
      "viewport_fit": "cover"
    },
    "ios": {
      "device_family": "any",
      "package_name": "%ios_package_name%",
      "disable_web_storage_backup": true,
      "webview": "WKWebView"
    }
  },
  "flags": {
    "migrate_web_storage_for_webview": %enable_storage_migration%,
    "move_filescheme_storage_to_httpscheme": %enable_storage_migration%,
    "android_workaround_transparent_statusbar_keyboard_bug": true,
    "ios_also_set_css_safe_area_inset_env_as_var": true
  },
  "modules": {
    "contact": {
      "version": "2.12",
      "config": {
        "usage_description": "Allow access to your contacts in order to recommend the app."
      },
      "disabled": %disable_recommend_module%
    },
    "icons": {
      "version": "2.9",
      "config": {
        "android": {
          "48": "img/native/android/icon-48.png",
          "72": "img/native/android/icon-72.png",
          "96": "img/native/android/icon-96.png",
          "144": "img/native/android/icon-144.png",
          "192": "img/native/android/icon-192.png",
          "adaptive": {
            "108": "img/native/android/icon-47.png",
            "162": "img/native/android/icon-70.png",
            "216": "img/native/android/icon-93.png",
            "324": "img/native/android/icon-140.png",
            "432": "img/native/android/icon-186.png",
            "background-color": "%android_adaptive_icon_background-color%"
          }
        },
        "ios": {
          "57": "img/native/ios/icons/icon-57.png",
          "72": "img/native/ios/icons/icon-72.png",
          "76": "img/native/ios/icons/icon-76.png",
          "114": "img/native/ios/icons/icon-114.png",
          "120": "img/native/ios/icons/icon-120.png",
          "144": "img/native/ios/icons/icon-144.png",
          "152": "img/native/ios/icons/icon-152.png",
          "167": "img/native/ios/icons/icon-167.png",
          "180": "img/native/ios/icons/icon-180.png",
          "1024": "img/native/ios/icons/icon-1024.png",
          "prerendered": true
        }
      }
    },
    "launchimage": {
      "version": "2.13",
      "config": {
        "android": {
          "portrait": "img/native/android/launchimage.png",
          "landscape": "img/native/android/launchimage.png",
          "background-color": "%android_launchimage_background-color%",
          "background-size": "%android_launchimage_background-size%"
        },
        "ios": {
          "wC_hC": "img/native/ios/launchimages/iphone-compact-landscape.png",
          "wR_hC": "img/native/ios/launchimages/iphone-landscape.png",
          "wC_hR": "img/native/ios/launchimages/iphone-portrait.png",
          "wR_hR": "img/native/ios/launchimages/ipad-landscape.png"
        },
        "hide-manually": true
      }
    },
    "display": {
      "version": "2.11",
      "config": {
        "statusbar": {
          "android": {
            "transparent": true
          },
          "ios": {}
        },
        "orientations": {
          "ipad": "any",
          "android": "any",
          "iphone": "portrait"
        }
      }
    },
    "file": {
      "version": "2.24",
      "config": {
        "usage_description": "Allow access in order to upload pictures and videos to the app."
      },
      "disabled": %disable_file_module%
    },
    "capture": {
      "version": "2.24",
      "config": {
        "usage_description": "Allow access in order to upload pictures and videos to the app."
      }
    },
    "notification": {
      "version": "2.8",
      "config": {}
    },
    "bolts": {
      "version": "1.9.0",
      "config": {}
    },
    "urlhandler": {
      "version": "2.2",
      "config": {
        "scheme": "xxxxxxxxxx"
      }
    },
    "request": {
      "version": "2.11",
      "config": {}
    },
    "share": {
      "version": "1.3",
      "config": {}
    },
    "prefs": {
      "version": "2.2",
      "config": {}
    },
    "browsersettings": {
      "version": "1.6",
      "config": {
        "accept_cookies": true,
        "media_playback": {
          "inline_video": false,
          "autoplay_video": true,
          "enable_html5_audio": true,
          "enable_background_audio": false,
          "respect_playing_audio": true
        }
      }
    },
    "utils": {
      "version": "0.67",
      "config": {
        "initialStatusBarStyle": "light_content"
      }
    },
    "platform": {
      "version": "2.3",
      "config": {}
    }
  }
}
```

</details>

App Source: 
<details>

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
  <title>The title</title>

  <style type="text/css">
    :root {
      --custom-safe-area-inset-top: var(--safe-area-inset-top);
    }
    html {
      height: 100vh;
      width: 100vw;
    }
    body {
      padding-top: var(--safe-area-inset-top);
      border: 1px solid red;
      margin: 0;
      background-color: lightblue;
    }
    div {
      border: 1px dashed green;
    }
  </style>
</head>
<body>
<div>Some nice text!1!<br/>More text</div>

<script>
  var supportCssVar = window.CSS.supports('padding-top: var(--custom-safe-area-inset-top)');
  console.log('CSS var support: ', supportCssVar);
  window.forge.internal.call('layout.setStatusBarTransparent', {transparent: false});
  window.forge.launchimage.hide();
</script>
   <textarea></textarea>
</body>
</html>
```

</details>

**To Reproduce**

1. Open the app
2. Click into the text area

**Expected behaviour**
 
The keyboard should open and I can still see and use my app.

**Actual behaviour**

A white block appears above the keyboard and "shrinks" the webview.

**Related information:**

Maybe: https://github.com/trigger-corp/forge/issues/23

**Comment by marwonline** [comment] 2019-10-15 07:42
The screenshots. Before focusing the text area: 
<details>

![IMG_20191015_092331](https://user-images.githubusercontent.com/25180025/66810627-ecfcc280-ef2f-11e9-9900-e61fb8b62cd0.jpg)
</details>

after focusing the text area:
<details>

![IMG_20191015_092144](https://user-images.githubusercontent.com/25180025/66810652-f6862a80-ef2f-11e9-9b8c-dcaeffa9b745.jpg)


</details>

**Comment by marwonline** [comment] 2019-10-16 06:43
Just realized that the Nexus 5X (Android 8.1.0) is also affected.

**Comment by antoinevg** [comment] 2019-10-16 14:28
Thank you for the report, I haven't seen this one for years!

What's happening here is that Android automatically adjusts the size of the view in response to the appearance of the keyboard.

Normally it's not a problem as most Android devices will sensibly adjust the view size relative to the keyboard size but some devices will instead adjust it relative to the size of the view's  content.

The traditional workaround for this has been to add a `<activity ... android:windowSoftInputMode="adjustPan">...</activity>` entry to the app's `AndroidManifest.xml` file.

You can do this either via a custom module or by editing your `src/config.json` file and adding the following entry to `core.general.android`:

    "android": {
        "windowSoftInputMode": "adjustPan"
    }

More info: https://developer.android.com/guide/topics/manifest/activity-element#wsoft

**Comment by marwonline** [comment] 2019-10-21 07:23
Sorry for the late reply. 

Thanks for providing the fix. Using this config parameter fixed the issue on all of our test devices.

**Comment by scthi** [comment] 2019-11-12 13:27
@antoinevg Unfortunately we encounter issues with this in tabs module (v3.2) on S5:

url of tabs module: https://app.peakon.com

**Expected (without windowSoftInputMode):**
<details>
<img src="https://user-images.githubusercontent.com/318533/68675341-f2adee00-0557-11ea-9b86-80d6b8c73e5f.jpg">
</details>

**Actual (with windowSoftInputMode):**

<details>
<img src="https://user-images.githubusercontent.com/318533/68675599-7f58ac00-0558-11ea-9052-7e74aad2c2f2.jpg">
</details>

**Comment by antoinevg** [comment] 2019-11-18 08:40
Does it make a difference if you mess with the Status Bar settings? i.e. turn it on/off, solid/transparent?

I vaguely remember this from a few years back. It was eventually fixed on Google's side but it looks like we now have a regression.

How many of your customers are still using S4/S5's ?

**Comment by scthi** [comment] 2019-11-18 10:23
> Does it make a difference if you mess with the Status Bar settings? i.e. turn it on/off, solid/transparent?

I tried to 
* turn off `flags.android_workaround_transparent_statusbar_keyboard_bug`
* set `display.config.statusbar.android.transparent` to `false`

without noticing any visual change on S5.

Only setting  set `display.config.statusbar.android.hidden` to `true` made a change, but looks even more broken:

<details>
<img width="512" alt="statusbar-hidden" src="https://user-images.githubusercontent.com/318533/69044439-3c358780-09f5-11ea-82c1-cdb407efc806.png">
</details>

> How many of your customers are still using S4/S5's ?

I don't have the precise numbers at hand, but afaik dropping the support is not an option atm.

**Comment by Manonisch** [comment] 2020-04-28 17:34
@antoinevg Hi, has there been any update on the issue?
This issue also appears on Android 9 for Huawei P20 Lite. When the Keyboard is open, notch recognition for bottom notch seems to fail. Trying to access the bottom notch via safe-area-inset-variables leads to the area being recognized as 0 height, while top notch is detected correctly.

When keyboard is closed
<details><summary>Details</summary>
<p>
<img  width="350" src="https://user-images.githubusercontent.com/16826487/80518039-3cfc1d80-8986-11ea-950a-e07a65a9b142.jpg"/>
</details>

When keyboard is open
<details><summary>Details</summary>
<p>
<img  width="350" src="https://user-images.githubusercontent.com/16826487/80518040-3d94b400-8986-11ea-8080-523c6e22c6f0.jpg"/>
</details>

**Comment by antoinevg** [comment] 2020-04-29 08:04
No updates. The behavior with Samsung S4/S5 is due to a regression on Google's part and the old workarounds are also no longer effective.

Can you please open a new issue for the issues you're having with the Huawei device and also attach the code for your test app?

(I did check and can't replicate it on my side but I have a Huawei P30 Lite so the issue may be limited to only the P20.)

Can you please also give a bit more info about what you mean by "bottom notch"? The Huawei P20/P30 phones both only have a top notch so I suspect I'm thinking of the wrong thing :-)

Thanks!

**Closed as completed** 2024-01-04 10:10 UTC
Labels: vendor bug
